### ISSUE TITLE
[FEAT] 영화 TableView 구현

### ISSUE THREAD

**Issue by binisnil** [GO-SOPT-iOS-Part/ParkYunBin#5]
## TO-DO

- [x] TMDB API -> now_playing api 사용해서 상영 중인 영화 목록 불러오기
- [x] 영화 정보 받아올 TableView UI 구현
- [x] TableViewCell에 API로 받아온 정보 붙이기
